name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          eho "build going on"
          sleep 10
      - name: Create a file
        run: touch /tmp/gagandeep1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test cases
        run: |
          echo "Test running"
          sleep 10
    needs: build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Do deployment
        run: |
          echo "deployment being done"
          sleep 10
    needs: test
