name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: echo "build going on"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
      - name: Create a file
        run: touch /tmp/gagandeep1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test cases
        run: echo "Test running"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Do deployment
        run: echo "deployment being done"
