name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cho "build going on"  ## Mistake to fail the build job
          sleep 10
      - name: Create a file
        run: touch /tmp/gagandeep1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test cases
        run: |
          echo "Test running"
          sleep 10
    needs: build   ## Will only run after successful completion of build job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Do deployment
        run: |
          echo "deployment being done"
          sleep 10
    if: ${{ always() }}
    needs: build 
    ## Will run even after unsuccessful completion of build job
